apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-edu-goods-deployment
  namespace: edu-goods
spec:
  selector:
    matchLabels:
      app: k8s-edu-goods-app
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-edu-goods-app
        version: blue
    spec:
      containers:
        - name: k8s-edu-goods-app
          image: jinunkim/k8s-goods:0.0.3      # dockerhub image repository : repo/image명:Tag
          imagePullPolicy: Always        # Sync
          ports:
            - name: http
              containerPort: 8080              # demo.jar 실행 포트
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080  # 어플리케이션이 리스닝하는 포트
            initialDelaySeconds: 5  # 컨테이너 시작 후 처음 검사까지 대기 시간
            periodSeconds: 10  # 검사 간격 (10초마다 상태 체크)
            failureThreshold: 3  # 실패가 연속으로 3번 발생하면 재시작
            timeoutSeconds: 2  # 프로브의 응답을 기다리는 시간 (2초)
          resources:                           # pod 사용 리소스 설정 블록
            requests:                          # 생성시 필요한 최소 리소스
              cpu: "1"
              memory: "2Gi"
            limits:                            # pod가 사용 가능한 최대 리소스
              cpu: "1"
              memory: "2Gi"
          env:                                 # pod 내 환경 변수 설정
            - name: SPRING_PROFILES_ACTIVE     # spring profile 설정
              value: prod                      # 상용(prod) 환경
      imagePullSecrets:                        # dockerhub 이미지 pull 위한 secret
        - name: k8s-edu-dockerhub-secret
      #nodeSelector:                            # pod가 실행 될 node 설정
        #kubernetes.io/hostname: worker01
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-edu-goods-hpa
  namespace: edu-goods
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-edu-goods-deployment  # HPA가 참조할 Deployment 이름
  minReplicas: 2  # 최소 2개 파드
  maxReplicas: 3  # 최대 3개 파드
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30  # CPU 사용량이 30% 이상일 때 1개씩 확장
